name: Living Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Denvironment=with_screenshots

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/site/serenity # The folder the action should deploy.
