name: Chapter 14 - Serenity/JS examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (Flying High App)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: flying-high-app

      - name: Install Node Modules (Chapter 14)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: chapter-14

      - name: Test
        working-directory: chapter-14
        run: npm test

      - name: Archive Serenity BDD reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          retention-days: 3
          name: chapter-14-reports
          path: |
            chapter-14/target/**/*
