# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Chapter 7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chapter-07/java/flying-high

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn -B verify

  build-typescript:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chapter-07/typescript/flying-high

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install node modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
