name: Chapter 12 Membership API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules (all)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: chapter-12/membership-api

      - name: Build
        working-directory: chapter-12/membership-api
        run: npm run build --if-present

      - name: Test
        working-directory: chapter-12/membership-api
        run: npm test
